version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: 'no'
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: false
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    restart: 'no'
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    # ports:
    # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  backend:
    build: ./backend/
    volumes:
      - ./backend/:/fullstack-backend/
    ports:
      - '8000:8000'

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/fullstack-frontend/
      - .:/fullstack/
    ports:
      - '3000:3000'

volumes:
  mysql:
