// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package fullstack_backend

type LikeInput struct {
	User     string `json:"user"`
	Post     string `json:"post"`
	Quantity int    `json:"quantity"`
}

type Message struct {
	Message string `json:"message"`
}

type PostInput struct {
	Text   string `json:"text"`
	Author string `json:"author"`
}

type UserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
