// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package fullstack_backend

type Like interface {
	IsLike()
}

type CommentInput struct {
	Body string `json:"body"`
	User string `json:"user"`
	Post string `json:"post"`
}

type CommentLikeInput struct {
	LikeInfo *LikeInput `json:"likeInfo"`
	Comment  string     `json:"comment"`
}

type LikeInput struct {
	Quantity int    `json:"quantity"`
	User     string `json:"user"`
}

type Message struct {
	Message string `json:"message"`
}

type PostInput struct {
	Author string `json:"author"`
	Header string `json:"header"`
	Body   string `json:"body"`
}

type PostLikeInput struct {
	LikeInfo *LikeInput `json:"likeInfo"`
	Post     string     `json:"post"`
}

type UpdatePostInput struct {
	Header string `json:"header"`
	Body   string `json:"body"`
}

type UserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
